import Head from 'next/head';
import Image from 'next/image';
import Slider from '../comps/Slider';
import styles from '../styles/Home.module.css';

const images = ['/thaiPage.png', '/resumePage.png', '/iphonePage.png'];

const titles = [
  ['Thai List', 'Resume', 'Landing Page'],
  ['Stack', 'Hurdles', 'Concept'],
];

const descriptions = [
  [
    'Nextjs, Strapi, Heroku, Javascipt, Xml, Css',
    'Getting query syntax correct when filtering for id. Connecting with Strapi & Heroku. Coming up with an original idea for the app',
    'A practical place to learn thai. Only most used words and phrases are listed. With break down meaning of each word,which many sites dont provide.',
  ],
  [
    'Nextjs, Javascipt, Xml, Css',
    'Creating polaroid slides. Making scroll snap into right section. Coming up with a minimal design',
    'A simple yet unique resume, stand out colour palette. Only include essential content. Rule of 3 applied in navbar, slides, and sections',
  ],
  [
    'Html, Css',
    'Creating a navbar for the first time. Getting the background to blend and fit. Using iframe for the first time',
    'A basic landing page. Blog like content. Easy to read',
  ],
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
        <section className={styles.sliderSection}>
          <Slider images={images} titles={titles} descriptions={descriptions} />
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
